apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: rustyalias-strace
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./profiles
    containerPath: /var/lib/kubelet/seccomp/profiles
    readOnly: false
- role: worker
  extraMounts:
  - hostPath: ./profiles
    containerPath: /var/lib/kubelet/seccomp/profiles
    readOnly: false